# Generated by Django 3.1.2 on 2020-10-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymclass', '0003_auto_20201018_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
