# Generated by Django 3.1.2 on 2020-10-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymclass', '0004_auto_20201019_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='type',
            new_name='class_type',
        ),
    ]
